services:
  #Бэкенд
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - app-network
    restart: unless-stopped


  #PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: backend-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  #Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: backend-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    restart: unless-stopped

  #Redis
  redis:
    image: redis:7-alpine
    container_name: backend-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped


#Сети и тома
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  es_data:
  redis_data:
